Qt: fix compile error when ODR check enabled.
when two structs with the same name, the linker many be confused. when LTO
is enabled, ODR checked is required.

```
parallel_chip_info.cpp:36:3: error: type ‘struct Conf’ violates the C++ One Definition Rule [-Werror=odr]
   36 | } Conf;
      |   ^
spi_chip_info.cpp:20:3: note: a different type is defined in another translation unit
   20 | } Conf;
```

Signed-off-by: Sasasu <i@sasa.su>